### ISSUE TITLE
Implement -  ClearCacheOnClient

### ISSUE THREAD

**Issue by kgmadsen** [d365collaborative/ax2012.tools#37]
How about implement a function/Command to clear the cache on the AX client

This will remove all *.auc, *.kti -files and assamblies in the LOCALAPPDATA folder for the User.    

You could call it : Invoke-ClearCacheOnClient
See attached file:
(https://github.com/d365collaborative/ax2012.tools/files/2775446/AxClearCacheOnClient.zip)

**Comment by Splaxi** [comment]
Should be part of the 0.1.16 release.

```
Get-Help Clear-AxClientCacheObjects -Full
```
