### ISSUE TITLE
Implement - ClearCacheOnServer

### ISSUE THREAD

**Issue by kgmadsen** [d365collaborative/ax2012.tools#38]
How about implement a function/Command to clear the cache on the AOS Server

This will remove all files in the XppIL-folder, the Ax*files in the Appl\Standard-folder and all the files in the VSAssemblies-folder

You could call it: Invoke-ClearCacheOnServer
See attached file:

[AxClearCacheOnServer.zip](https://github.com/d365collaborative/ax2012.tools/files/2775452/AxClearCacheOnServer.zip)

**Comment by Splaxi** [comment]
Should be part of the 0.1.16 release.

```
Get-Help Clear-AxServerCacheObjects -Full
```
