### ISSUE TITLE
HASH-Code Check of Xppil-files on Each AOS Server

### ISSUE THREAD

**Issue by kgmadsen** [d365collaborative/ax2012.tools#39]
Some developers seems to implement code on AOS Server in Live PROD, from time to time... 
 
This function is a way to create a file with all the HASH values for each *.netmodule and *.dll files in the XppIL-folder of a given AOS server... 

The Idea is to Collect all the files for each AOS server and then compare the files.... ANY deviation will be an indeaction that someone has messed with the AOS which can lead to serious errors...

I imagine the attached script extende so it can be executed on each AOS, then collect all the Files and then be compared, and present an outcome of "CIL is Ok" or "Errors In CIL" 

[AxXppCILCompare.zip](https://github.com/d365collaborative/ax2012.tools/files/2775467/AxXppCILCompare.zip)

**Comment by Splaxi** [comment]
It should be part of the 0.1.17 release

```
Get-AxServerXppILHash
```
